pipeline {
    agent any

    environment {
        PM_API_TOKEN_ID = credentials('pm-api-token-id')
        PM_API_TOKEN_SECRET = credentials('pm-api-token-secret')
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
    }

    stages { // Only one stages block
        stage('init') {
            agent {
                docker {
                    image 'hashicorp/terraform:1.12.2'
                    args '--entrypoint=""'
                }
            }
            steps {
                dir('cluster-k8s/terraform') {
                    sh '''
                        terraform init -no-color
                    '''
                }
            }
        }

        stage('plan') {
            agent {
                docker {
                    image 'hashicorp/terraform:1.12.2'
                    args '--entrypoint=""'
                }
            }
            steps {
                dir('cluster-k8s/terraform') {
                    sh '''
                        terraform plan -no-color
                    '''
                }
            }
        }
    }
}