stage('init') {
      agent {
        docker {
          image 'hashicorp/terraform:1.12.2'
          args '--entrypoint=""'
        }
      }
      steps {
        dir('homelab/cluster-k8s/terraform') {
          sh '''
            terraform init -no-color
          '''
        }
      }
    }